import { Inter } from 'next/font/google';
import './globals.css';
import { SongProvider } from '@/contexts/AudioContext';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-svh bg-black text-neutralViolet-50`}
      >
        <SongProvider>{children}</SongProvider>
      </body>
    </html>
  );
}
