import { Inter } from 'next/font/google';
import './globals.css';
import { SongProvider } from '@/contexts/AudioContext';
import { MicrophoneProvider } from '@/contexts/MicrophoneContext';

const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo1.ico', // Ruta correcta desde la carpeta public
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} h-svh bg-black text-neutralViolet-50`}
      >
        <MicrophoneProvider>
          <SongProvider>{children}</SongProvider>
        </MicrophoneProvider>
      </body>
    </html>
  );
}
